language: php
sudo: false
before_script:
- free -m
- >
    if [ "$PHPUNIT_SUITE" != "unit" ]; then
        phpenv config-rm xdebug.ini
    fi
- echo "memory_limit=2G"  >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
- composer install --no-interaction  --ignore-platform-reqs --no-scripts --profile
- >
    if [ "$PHPUNIT" = "true" ]; then
        wget https://scrutinizer-ci.com/ocular.phar
    fi
php:
- 5.6
env:
  matrix:
    - COMPOSER_CHECK=true PHPUNIT=false
    - COMPOSER_CHECK=false PHPUNIT=true PHPUNIT_SUITE=unit
matrix:
  exclude:
  - php: 5.6
    env: COMPOSER_CHECK=true PHPUNIT=false
script:
    if [ "$COMPOSER_CHECK" = "true" ]; then
        composer check;
    fi
notifications:
  hipchat:
    rooms:
      secure: F5pTVtwBACRIXMdkQ/oE6f5faK3eHvPqDmD7jmAv4vU7Nyog4RN1h1nqa8kJo6fRaRvdbIF5ovAwfdX5nuoMBQqio4FpfpT4jkfFNf5gGEFOlGW3UTQR/8JyoVCEvZ4Wau3OsIouv1U3du9uWvaqHoxIeI9HvnTVinSzu9P4EjE=
    on_success: change
    on_failure: always

cache:
    directories:
    - vendor/
