language: php
sudo: false
services:
- mongodb
- rabbitmq
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_script:
- free -m
- >
    if [ "$PHPUNIT_SUITE" != "integration" ]; then
        export MONGODB_URI=mongodb://does.not.exist.example.org:443
    fi
- >
    if [ "$PHPUNIT_SUITE" != "unit" ]; then
        phpenv config-rm xdebug.ini
    fi
- >
    if [ $(phpenv version-name) != "7.0" ]; then
        echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
    fi
- >
    if [ $(phpenv version-name) = "7.0" ]; then
        # installing mongofill requires more than 1GB of RAM
        echo "memory_limit=3G"  >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
        composer require mongofill/mongofill:dev-master --ignore-platform-reqs --profile --no-scripts;
    fi
- composer install --no-interaction  --ignore-platform-reqs --no-scripts --profile
- >
    if [ "$PHPUNIT" = "true" ]; then
        wget https://scrutinizer-ci.com/ocular.phar
    fi
php:
- 7.0
- 5.6
env:
  matrix:
    - COMPOSER_CHECK=false PHPUNIT=true PHPUNIT_SUITE=integration
    - COMPOSER_CHECK=true PHPUNIT=false
    - COMPOSER_CHECK=false PHPUNIT=true PHPUNIT_SUITE=unit
matrix:
  exclude:
  - php: 5.6
    env: COMPOSER_CHECK=true PHPUNIT=false
script:
- >
    if [ "$PHPUNIT" = "true" ]; then
        composer run-script post-install-cmd && \
        touch src/Graviton/I18nBundle/Resources/translations/i18n.de.odm && \
        touch src/Graviton/I18nBundle/Resources/translations/i18n.es.odm && \
        if [ "$PHPUNIT_SUITE" == "integration" ]; then
            php app/console graviton:generate:build-indexes
        fi && \
        if [ "$PHPUNIT_SUITE" == "unit" ]; then
          COVERAGE=" --coverage-clover=coverage.clover "
        fi && \
        vendor/bin/phpunit $COVERAGE --testsuite=$PHPUNIT_SUITE && \
        if [ $COVERAGE ]; then
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
        fi
    fi
- >
    if [ "$COMPOSER_CHECK" = "true" ]; then
        composer check;
    fi
notifications:
  hipchat:
    rooms:
      secure: F5pTVtwBACRIXMdkQ/oE6f5faK3eHvPqDmD7jmAv4vU7Nyog4RN1h1nqa8kJo6fRaRvdbIF5ovAwfdX5nuoMBQqio4FpfpT4jkfFNf5gGEFOlGW3UTQR/8JyoVCEvZ4Wau3OsIouv1U3du9uWvaqHoxIeI9HvnTVinSzu9P4EjE=
    on_success: change
    on_failure: always

cache:
    directories:
    - vendor/
