Graviton\AuditTrackingBundle\Document\AuditTracking:
  fields:
    id:
      id: true
      strategy: UUID
    thread:
      type: string
    username:
      type: string
    action:
      type: string
    type:
      type: string
    collectionId:
      type: string
    collectionName:
      type: string
    data:
      type: raw
    createdAt:
      type: date

  indexes:
      auditIdx:
        keys:
          collectionName: asc
          collectionId: asc
          createdAt: asc
        options:
          name: auditIdx
          background: true
