<?php
/**
 * document repository for Graviton\AuditTrackingBundle\Repository\ActivityLog
 */

namespace Graviton\AuditTrackingBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Graviton\AuditTrackingBundle\Repository\ActivityLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author   List of contributors <https://github.com/libgraviton/graviton/graphs/contributors>
 * @license  https://opensource.org/licenses/MIT MIT License
 * @link     http://swisscom.ch
 */
class AuditTrackingRepository extends DocumentRepository
{
}
